version: '3.9'
services:
    app:
        build:
            context: .docker/dev/php
            dockerfile: Dockerfile
            args:
                INSTALL_XDEBUG: ${DOCKER_INSTALL_XDEBUG:-false}
        working_dir: /application
        environment:
            - DOCKER=1
            - PHP_IDE_CONFIG=serverName=plan.local
        volumes:
            - ./.docker/dev/ngnix/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./.docker/dev/php/php.ini:/usr/local/etc/php/conf.d/zzz-overrides.ini:ro
            - ./.docker/dev/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-overrides.conf:ro
            - ./.docker/dev/php/supervisord.conf:/etc/supervisor/custom-supervisord.conf:ro
            - .:/application
        ports:
            - ${EXTERNAL_APP_PORT:-80}:80
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - plan
    db:
        image: postgres:16
        ports:
            - ${FORWARD_DB_PORT:-5432}:5432
        environment:
            PGPASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - /var/lib/postgresql/data
        networks:
            - plan
    redis:
        image: redis:7.0.11-alpine3.17
        ports:
            - ${DOCKER_REDIS_HOST_PORT:-6379}:6379
        networks:
            - plan
        restart: unless-stopped
# Networks
networks:
    plan:
        driver: bridge
